# Generated by Django 5.2 on 2025-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('tipo_asistencia', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('verificado_biometrico', models.BooleanField(default=False)),
            ],
        ),
    ]
