# Generated by Django 5.2 on 2025-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencias', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.horario'),
        ),
    ]
