# Generated by Django 5.2 on 2025-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificacion', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubclasificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subclasificacion', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificacion.clasificacionproducto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral')),
            ],
        ),
    ]
