# Generated by Django 5.2 on 2025-09-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cierres', '0001_initial'),
        ('clientes', '0001_initial'),
        ('cupones', '0001_initial'),
        ('estados', '0001_initial'),
        ('promociones', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venta', models.CharField(max_length=50, unique=True)),
                ('fecha_hora_venta', models.DateTimeField()),
                ('descripcion_venta', models.TextField(blank=True, null=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_venta', models.CharField(max_length=50)),
                ('forma_pago', models.CharField(max_length=50)),
                ('cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cierres.cierreventa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupones.cupon')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promocion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
