# Generated by Django 5.2 on 2025-09-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_documento_sector', models.CharField(max_length=50)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('cuf', models.CharField(max_length=100, unique=True)),
                ('punto_venta', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_venta', models.TextField(blank=True, null=True)),
                ('ICE', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('IEHD', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('JPJ', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_NSCF', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_cero', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gift_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ajuste_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autorizacion_contingencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_emision', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
