# Generated by Django 5.2 on 2025-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aguinaldos', '0001_initial'),
        ('contratos', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aguinaldo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral'),
        ),
    ]
