# Generated by Django 5.2 on 2025-09-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_precio', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='menu.menu')),
            ],
        ),
    ]
