# Generated by Django 5.2 on 2025-09-06 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('incremento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.estadogeneral')),
            ],
        ),
    ]
