# Generated by Django 5.2 on 2025-09-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('subclasificaciones_menu', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='subclasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subclasificaciones_menu.subclasificacionmenu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('nombre_menu', 'sucursal')},
        ),
    ]
