# Generated by Django 5.2 on 2025-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('subclasificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subclasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subclasificaciones.subclasificacionproducto'),
        ),
    ]
